### ISSUE TITLE
Crash when starting

### ISSUE THREAD

**Issue by LCTMarti** [VoidSorc/Total-Tinkers#6]
Log:

Description: Initializing game

java.lang.NullPointerException: Initializing game
	at uvmidnight.totaltinkers.TotalTinkersRegister.onRegisterPotions(TotalTinkersRegister.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_105_TotalTinkersRegister_onRegisterPotions_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at uvmidnight.totaltinkers.TotalTinkersRegister.onRegisterPotions(TotalTinkersRegister.java:64)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_105_TotalTinkersRegister_onRegisterPotions_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

===========================

Mods:
Armory Expansion		
Construct's Armory	
Just Enough Items (JEI)	
Kyth's Overpowered Moss	
Mantle
Mekanism		
Oreberries	
Pewter	
PlusTiC	
Shadowfacts' Forgelin		
Tinkers Construct		
Tinkers' MEMES	
Tinkers' Modifier Modifier	
Tinkers' Tool Leveling	
Tool Progression
Total Tinkers		
Tweakers Construct

**Comment by CvoidWyvern** [comment]
I also had this crash, version 0.4.2, downgrading to 0.3.1 fixed it.

similarity in modlist:
JEI
Mantle
Mekanism
PlusTIC
Shadowfacts' Forgelin
Tinkers Construct
Total Tinkers

**Comment by UvMidnight** [comment]
Woops... Sorry, should have looked at this a long time ago. this was an error with the modularity code, disabling modules completely just crashed the game. 0.4.2 disabled the experimental module by default. 0.3.1 was before the introduction of the experimental module, which is why that stopped the crash. This was fixed with 0.4.3
